### ISSUE TITLE
UnicodeDecodeError:  when running with python 3

### ISSUE THREAD

**Issue by bebef1987** [mozilla-releng/tooltool#23] opened 2020-01-22 15:56 UTC
I see this error when trying to download a manifest file from tooltool
manifest:
https://searchfox.org/mozilla-central/source/testing/mozbase/mozproxy/mozproxy/backends/mitm/mitmproxy-rel-bin-4.0.4-win.manifest

command line: `python3.6 tooltool.py fetch -o -m <manifets path>`

```
    /mozilla/tooltool/client$ python3.6 tooltool.py fetch -o -m /home/florinstrugariu/mozilla/mozilla-central/testing/mozbase/mozproxy/mozproxy/backends/mitm/mitmproxy-rel-bin-4.0.4-win.manifest 
    INFO - Attempting to fetch from 'https://tooltool.mozilla-releng.net/'...
    INFO - ...failed to fetch 'mitmproxy-4.0.4-windows.zip' from https://tooltool.mozilla-releng.net/
    Traceback (most recent call last):
      File "tooltool.py", line 741, in fetch_file
        indata = to_text(indata)
      File "tooltool.py", line 99, in to_text
        return val.decode('utf-8')
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xad in position 10: invalid start byte
    ERROR - The following files failed: 'mitmproxy-4.0.4-windows.zip'
```

**Comment by mozbhearsum** [comment] 2020-02-19 15:54
At this point, 3.6 is Old (3.8.1 is already out). I don't think it's worth fixing this unless it's reproducible on 3.7 or 3.8.

**Comment by tarekziade** [comment] 2020-02-19 17:31
@mozbhearsum you should reopen this bug, it will happen on 3.7 and 3.8 as well.

The bug is that for some reason, the PY3 version is not saving the data using a binary mode. it converts for some reason the data received into text and then writes it into a text file.

But it makes the assumption that the data received can always be decoded in utf8, which is not the case all the time (and the response headers don't always give us a hint and we don't check it anyways)

We should keep the 'wb' mode for py3 too and simply write through the data received as bytes.
I got it working locally, happy to provide a PR is needed.

**Comment by tarekziade** [comment] 2020-02-19 17:34
This is my quick fix to make it work locally :)

```
tarek@Tareks-MacBook-Air-3 Downloads % diff tooltool.py.original tooltool.py.mine
63c63
<     open_attrs = dict(mode='w', encoding='utf-8')
---
>     open_attrs = dict(mode='wb')  #, encoding='utf-8')
740,741c740,741
<                     if PY3:
<                         indata = to_text(indata)
---
>                     #if PY3:
>                     #    indata = to_text(indata)
```

**Comment by mozbhearsum** [comment] 2020-02-19 17:54
Okay, let's reopen then :)

**Comment by bebef1987** [comment] 2020-02-20 12:59
This is blocking a mozproxy enhancement: https://phabricator.services.mozilla.com/D62443

Here is a try example of the error:
https://treeherder.mozilla.org/#/jobs?repo=try&selectedJob=289676975&revision=73a706c3397b0ed213c6727f2a347d3e375d6608

**Comment by tarekziade** [comment] 2020-02-20 13:05
We're far away from vendoring tooltool (that's the plan)
In the meantime for this bug what I propose we do is:

- fix it here
- copy over the new tooltool.py version in all tooltool.py instances in mozilla-central
- bump the version number in that file, it was never changed I think

**Comment by mozbhearsum** [comment] 2020-02-20 18:35
I have a plausible fix for this in #27, although it can't be merged yet due to test failures.

If anyone is up for it, I'd appreciate any additional testing you can do with the new tooltool.py.

**Comment by mozbhearsum** [comment] 2020-02-24 19:34
https://lando.services.mozilla.com/D63870/ to import the fix in tree.

**Comment by bebef1987** [comment] 2020-02-28 13:35
@mozbhearsum  looks like the import was backed out can you take a new look pls

**Comment by mozbhearsum** [comment] 2020-02-28 18:17
Yeah, sorry about that. I've got that fixed here, and will be updating `mozilla-central` again after https://github.com/mozilla-releng/tooltool/pull/28 lands.

In the meantime, feel free to import the current `tooltool.py` into try pushes if it helps you.

**Comment by mozbhearsum** [comment] 2020-03-03 16:34
#28 is taking a bit longer than I thought. I opened https://phabricator.services.mozilla.com/D65139 to get the python 3 support landed in the meantime.

**Comment by mozbhearsum** [comment] 2020-03-05 16:08
This landed on central and stuck this time. Python 3 _should_ work now. Please re-open or open a new issue if it's still problematic.

**Closed by mozbhearsum** 2020-03-05 16:08 UTC
